[WsServer]
Addr = "0.0.0.0"
Port = 8080
JwtSecret = "secret"
ID = "node1"

[IMRpcServer]
Addr = "0.0.0.0"
Port = 8092
Network = "tcp"
Etcd = []
Name = "im_rpc_server"

[MySql]
Host = "localhost"
Port = 3306
Username = "root"
Password = "root"
Db = "im-service"
Charset = "utf8mb4"